# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 568))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Wheel = QtWidgets.QWidget()
        self.Tab_Wheel.setObjectName("Tab_Wheel")
        self.tabWidget.addTab(self.Tab_Wheel, "")
        self.Tab_Hourglass = QtWidgets.QWidget()
        self.Tab_Hourglass.setObjectName("Tab_Hourglass")
        self.tabWidget.addTab(self.Tab_Hourglass, "")
        self.Tab_Hourglass_Wheel = QtWidgets.QWidget()
        self.Tab_Hourglass_Wheel.setObjectName("Tab_Hourglass_Wheel")
        self.tabWidget.addTab(self.Tab_Hourglass_Wheel, "")
        self.Tab_Manual = QtWidgets.QWidget()
        self.Tab_Manual.setObjectName("Tab_Manual")
        self.ST1_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST1_ON_Button.setGeometry(QtCore.QRect(10, 10, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST1_ON_Button.setFont(font)
        self.ST1_ON_Button.setObjectName("ST1_ON_Button")
        self.ST2_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST2_ON_Button.setGeometry(QtCore.QRect(10, 70, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST2_ON_Button.setFont(font)
        self.ST2_ON_Button.setObjectName("ST2_ON_Button")
        self.ST12_OFF_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST12_OFF_Button.setGeometry(QtCore.QRect(9, 130, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST12_OFF_Button.setFont(font)
        self.ST12_OFF_Button.setObjectName("ST12_OFF_Button")
        self.groupBoxSet_Speed = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Speed.setGeometry(QtCore.QRect(0, 180, 681, 101))
        self.groupBoxSet_Speed.setObjectName("groupBoxSet_Speed")
        self.lineEdit_Speed_IN = QtWidgets.QLineEdit(self.groupBoxSet_Speed)
        self.lineEdit_Speed_IN.setGeometry(QtCore.QRect(270, 31, 101, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lineEdit_Speed_IN.setFont(font)
        self.lineEdit_Speed_IN.setDragEnabled(False)
        self.lineEdit_Speed_IN.setReadOnly(True)
        self.lineEdit_Speed_IN.setObjectName("lineEdit_Speed_IN")
        self.button_Speed_m1 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m1.setGeometry(QtCore.QRect(190, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_m1.setFont(font)
        self.button_Speed_m1.setObjectName("button_Speed_m1")
        self.button_Speed_m10 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m10.setGeometry(QtCore.QRect(110, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_m10.setFont(font)
        self.button_Speed_m10.setObjectName("button_Speed_m10")
        self.button_Speed_m100 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m100.setGeometry(QtCore.QRect(10, 29, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_m100.setFont(font)
        self.button_Speed_m100.setObjectName("button_Speed_m100")
        self.button_Speed_p1 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p1.setGeometry(QtCore.QRect(380, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_p1.setFont(font)
        self.button_Speed_p1.setObjectName("button_Speed_p1")
        self.button_Speed_p10 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p10.setGeometry(QtCore.QRect(460, 30, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_p10.setFont(font)
        self.button_Speed_p10.setObjectName("button_Speed_p10")
        self.button_Speed_p100 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p100.setGeometry(QtCore.QRect(550, 30, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_Speed_p100.setFont(font)
        self.button_Speed_p100.setObjectName("button_Speed_p100")
        self.groupBoxSet_Acceleration = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Acceleration.setGeometry(QtCore.QRect(0, 280, 681, 101))
        self.groupBoxSet_Acceleration.setObjectName("groupBoxSet_Acceleration")
        self.lineEdit_Acceleration_IN = QtWidgets.QLineEdit(self.groupBoxSet_Acceleration)
        self.lineEdit_Acceleration_IN.setGeometry(QtCore.QRect(250, 30, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lineEdit_Acceleration_IN.setFont(font)
        self.lineEdit_Acceleration_IN.setDragEnabled(False)
        self.lineEdit_Acceleration_IN.setReadOnly(True)
        self.lineEdit_Acceleration_IN.setObjectName("lineEdit_Acceleration_IN")
        self.button_Acceleration_m1000 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m1000.setGeometry(QtCore.QRect(10, 30, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_m1000.setFont(font)
        self.button_Acceleration_m1000.setObjectName("button_Acceleration_m1000")
        self.button_Acceleration_m100 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m100.setGeometry(QtCore.QRect(100, 30, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_m100.setFont(font)
        self.button_Acceleration_m100.setObjectName("button_Acceleration_m100")
        self.button_Acceleration_m10 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m10.setGeometry(QtCore.QRect(180, 30, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_m10.setFont(font)
        self.button_Acceleration_m10.setObjectName("button_Acceleration_m10")
        self.button_Acceleration_p10 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p10.setGeometry(QtCore.QRect(410, 30, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_p10.setFont(font)
        self.button_Acceleration_p10.setObjectName("button_Acceleration_p10")
        self.button_Acceleration_p100 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p100.setGeometry(QtCore.QRect(480, 30, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_p100.setFont(font)
        self.button_Acceleration_p100.setObjectName("button_Acceleration_p100")
        self.button_Acceleration_p1000 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p1000.setGeometry(QtCore.QRect(570, 30, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_Acceleration_p1000.setFont(font)
        self.button_Acceleration_p1000.setObjectName("button_Acceleration_p1000")
        self.tabWidget.addTab(self.Tab_Manual, "")
        self.Tab_Settings = QtWidgets.QWidget()
        self.Tab_Settings.setObjectName("Tab_Settings")
        self.comboBoxSerialName = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialName.setGeometry(QtCore.QRect(180, 10, 261, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBoxSerialName.setFont(font)
        self.comboBoxSerialName.setObjectName("comboBoxSerialName")
        self.comboBoxSerialSpeed = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialSpeed.setGeometry(QtCore.QRect(180, 60, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBoxSerialSpeed.setFont(font)
        self.comboBoxSerialSpeed.setObjectName("comboBoxSerialSpeed")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.label_3 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_3.setGeometry(QtCore.QRect(5, 10, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_4.setGeometry(QtCore.QRect(5, 60, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_5.setGeometry(QtCore.QRect(5, 110, 251, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_Save_Settings = QtWidgets.QPushButton(self.Tab_Settings)
        self.pushButton_Save_Settings.setGeometry(QtCore.QRect(480, 150, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_Save_Settings.setFont(font)
        self.pushButton_Save_Settings.setObjectName("pushButton_Save_Settings")
        self.label_6 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_6.setGeometry(QtCore.QRect(5, 160, 141, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBoxMRJ_type = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxMRJ_type.setGeometry(QtCore.QRect(180, 160, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBoxMRJ_type.setFont(font)
        self.comboBoxMRJ_type.setObjectName("comboBoxMRJ_type")
        self.comboBoxMRJ_type.addItem("")
        self.comboBoxMRJ_type.addItem("")
        self.label_7 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_7.setGeometry(QtCore.QRect(5, 210, 261, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBoxStation_number = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxStation_number.setGeometry(QtCore.QRect(270, 210, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBoxStation_number.setFont(font)
        self.comboBoxStation_number.setObjectName("comboBoxStation_number")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxPeriodDate = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxPeriodDate.setGeometry(QtCore.QRect(180, 110, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBoxPeriodDate.setFont(font)
        self.comboBoxPeriodDate.setObjectName("comboBoxPeriodDate")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.tabWidget.addTab(self.Tab_Settings, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(700, 20, 301, 481))
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setObjectName("groupBox")
        self.lcdPosition = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdPosition.setEnabled(True)
        self.lcdPosition.setGeometry(QtCore.QRect(130, 40, 151, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.lcdPosition.setPalette(palette)
        self.lcdPosition.setMouseTracking(False)
        self.lcdPosition.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdPosition.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdPosition.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdPosition.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdPosition.setLineWidth(2)
        self.lcdPosition.setMidLineWidth(10)
        self.lcdPosition.setSmallDecimalPoint(False)
        self.lcdPosition.setDigitCount(9)
        self.lcdPosition.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdPosition.setProperty("value", 0.0)
        self.lcdPosition.setProperty("intValue", 0)
        self.lcdPosition.setObjectName("lcdPosition")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 50))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 50))
        self.label_2.setObjectName("label_2")
        self.lcdSpeed = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdSpeed.setEnabled(True)
        self.lcdSpeed.setGeometry(QtCore.QRect(190, 100, 91, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.lcdSpeed.setPalette(palette)
        self.lcdSpeed.setMouseTracking(False)
        self.lcdSpeed.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdSpeed.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdSpeed.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdSpeed.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdSpeed.setLineWidth(2)
        self.lcdSpeed.setMidLineWidth(10)
        self.lcdSpeed.setSmallDecimalPoint(False)
        self.lcdSpeed.setDigitCount(5)
        self.lcdSpeed.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdSpeed.setProperty("value", 0.0)
        self.lcdSpeed.setProperty("intValue", 0)
        self.lcdSpeed.setObjectName("lcdSpeed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionasda = QtWidgets.QAction(MainWindow)
        self.actionasda.setObjectName("actionasda")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRJ Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Wheel), _translate("MainWindow", "Wheel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass), _translate("MainWindow", "Hourglass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass_Wheel), _translate("MainWindow", "Hourglass-Wheel"))
        self.ST1_ON_Button.setText(_translate("MainWindow", "Forward rotation start"))
        self.ST2_ON_Button.setText(_translate("MainWindow", "Reverse rotation start"))
        self.ST12_OFF_Button.setText(_translate("MainWindow", "Stop rotation"))
        self.groupBoxSet_Speed.setTitle(_translate("MainWindow", "Set speed, r/min(0...3000)"))
        self.button_Speed_m1.setText(_translate("MainWindow", "-1"))
        self.button_Speed_m10.setText(_translate("MainWindow", "-10"))
        self.button_Speed_m100.setText(_translate("MainWindow", "-100"))
        self.button_Speed_p1.setText(_translate("MainWindow", "+1"))
        self.button_Speed_p10.setText(_translate("MainWindow", "+10"))
        self.button_Speed_p100.setText(_translate("MainWindow", "+100"))
        self.groupBoxSet_Acceleration.setTitle(_translate("MainWindow", "Set Acceleration, ms(500...20000)"))
        self.button_Acceleration_m1000.setText(_translate("MainWindow", "-1000"))
        self.button_Acceleration_m100.setText(_translate("MainWindow", "-100"))
        self.button_Acceleration_m10.setText(_translate("MainWindow", "-10"))
        self.button_Acceleration_p10.setText(_translate("MainWindow", "+10"))
        self.button_Acceleration_p100.setText(_translate("MainWindow", "+100"))
        self.button_Acceleration_p1000.setText(_translate("MainWindow", "+1000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Manual), _translate("MainWindow", "Manual"))
        self.comboBoxSerialSpeed.setItemText(0, _translate("MainWindow", "57600"))
        self.comboBoxSerialSpeed.setItemText(1, _translate("MainWindow", "38400"))
        self.comboBoxSerialSpeed.setItemText(2, _translate("MainWindow", "19200"))
        self.comboBoxSerialSpeed.setItemText(3, _translate("MainWindow", "9600"))
        self.label_3.setText(_translate("MainWindow", "Serial Name:"))
        self.label_4.setText(_translate("MainWindow", "Serial Speed:"))
        self.label_5.setText(_translate("MainWindow", "Period, ms:"))
        self.pushButton_Save_Settings.setText(_translate("MainWindow", "Save Settings"))
        self.label_6.setText(_translate("MainWindow", "MRJ type:"))
        self.comboBoxMRJ_type.setItemText(0, _translate("MainWindow", "J2S-xCL"))
        self.comboBoxMRJ_type.setItemText(1, _translate("MainWindow", "J2S-xA"))
        self.label_7.setText(_translate("MainWindow", "MRJ Station number:"))
        self.comboBoxStation_number.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxStation_number.setItemText(1, _translate("MainWindow", "1"))
        self.comboBoxStation_number.setItemText(2, _translate("MainWindow", "2"))
        self.comboBoxStation_number.setItemText(3, _translate("MainWindow", "3"))
        self.comboBoxStation_number.setItemText(4, _translate("MainWindow", "4"))
        self.comboBoxStation_number.setItemText(5, _translate("MainWindow", "5"))
        self.comboBoxStation_number.setItemText(6, _translate("MainWindow", "6"))
        self.comboBoxStation_number.setItemText(7, _translate("MainWindow", "7"))
        self.comboBoxStation_number.setItemText(8, _translate("MainWindow", "8"))
        self.comboBoxStation_number.setItemText(9, _translate("MainWindow", "9"))
        self.comboBoxStation_number.setItemText(10, _translate("MainWindow", "A"))
        self.comboBoxStation_number.setItemText(11, _translate("MainWindow", "B"))
        self.comboBoxStation_number.setItemText(12, _translate("MainWindow", "C"))
        self.comboBoxStation_number.setItemText(13, _translate("MainWindow", "D"))
        self.comboBoxStation_number.setItemText(14, _translate("MainWindow", "E"))
        self.comboBoxPeriodDate.setItemText(0, _translate("MainWindow", "50"))
        self.comboBoxPeriodDate.setItemText(1, _translate("MainWindow", "100"))
        self.comboBoxPeriodDate.setItemText(2, _translate("MainWindow", "150"))
        self.comboBoxPeriodDate.setItemText(3, _translate("MainWindow", "200"))
        self.comboBoxPeriodDate.setItemText(4, _translate("MainWindow", "250"))
        self.comboBoxPeriodDate.setItemText(5, _translate("MainWindow", "300"))
        self.comboBoxPeriodDate.setItemText(6, _translate("MainWindow", "350"))
        self.comboBoxPeriodDate.setItemText(7, _translate("MainWindow", "400"))
        self.comboBoxPeriodDate.setItemText(8, _translate("MainWindow", "450"))
        self.comboBoxPeriodDate.setItemText(9, _translate("MainWindow", "500"))
        self.comboBoxPeriodDate.setItemText(10, _translate("MainWindow", "550"))
        self.comboBoxPeriodDate.setItemText(11, _translate("MainWindow", "600"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Settings), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Current parameter MRJ"))
        self.label.setText(_translate("MainWindow", "Position: "))
        self.label_2.setText(_translate("MainWindow", "Speed: "))
        self.actionasda.setText(_translate("MainWindow", "asda"))

