# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 568))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 501))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Wheel = QtWidgets.QWidget()
        self.Tab_Wheel.setObjectName("Tab_Wheel")
        self.tabWidget.addTab(self.Tab_Wheel, "")
        self.Tab_Hourglass = QtWidgets.QWidget()
        self.Tab_Hourglass.setObjectName("Tab_Hourglass")
        self.tabWidget.addTab(self.Tab_Hourglass, "")
        self.Tab_Hourglass_Wheel = QtWidgets.QWidget()
        self.Tab_Hourglass_Wheel.setObjectName("Tab_Hourglass_Wheel")
        self.tabWidget.addTab(self.Tab_Hourglass_Wheel, "")
        self.Tab_Manual = QtWidgets.QWidget()
        self.Tab_Manual.setObjectName("Tab_Manual")
        self.ST1_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST1_ON_Button.setGeometry(QtCore.QRect(10, 10, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST1_ON_Button.setFont(font)
        self.ST1_ON_Button.setObjectName("ST1_ON_Button")
        self.ST2_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST2_ON_Button.setGeometry(QtCore.QRect(10, 70, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST2_ON_Button.setFont(font)
        self.ST2_ON_Button.setObjectName("ST2_ON_Button")
        self.ST12_OFF_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST12_OFF_Button.setGeometry(QtCore.QRect(9, 130, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ST12_OFF_Button.setFont(font)
        self.ST12_OFF_Button.setObjectName("ST12_OFF_Button")
        self.groupBoxSet_Speed = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Speed.setGeometry(QtCore.QRect(0, 180, 651, 101))
        self.groupBoxSet_Speed.setObjectName("groupBoxSet_Speed")
        self.lineEdit_Speed_IN = QtWidgets.QLineEdit(self.groupBoxSet_Speed)
        self.lineEdit_Speed_IN.setGeometry(QtCore.QRect(430, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lineEdit_Speed_IN.setFont(font)
        self.lineEdit_Speed_IN.setDragEnabled(False)
        self.lineEdit_Speed_IN.setReadOnly(True)
        self.lineEdit_Speed_IN.setObjectName("lineEdit_Speed_IN")
        self.spinBoxSpeed_IN_100X = QtWidgets.QSpinBox(self.groupBoxSet_Speed)
        self.spinBoxSpeed_IN_100X.setGeometry(QtCore.QRect(10, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxSpeed_IN_100X.setFont(font)
        self.spinBoxSpeed_IN_100X.setMinimum(0)
        self.spinBoxSpeed_IN_100X.setMaximum(2900)
        self.spinBoxSpeed_IN_100X.setSingleStep(100)
        self.spinBoxSpeed_IN_100X.setProperty("value", 2900)
        self.spinBoxSpeed_IN_100X.setObjectName("spinBoxSpeed_IN_100X")
        self.label_6 = QtWidgets.QLabel(self.groupBoxSet_Speed)
        self.label_6.setGeometry(QtCore.QRect(130, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinBoxSpeed_IN_10X = QtWidgets.QSpinBox(self.groupBoxSet_Speed)
        self.spinBoxSpeed_IN_10X.setGeometry(QtCore.QRect(150, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxSpeed_IN_10X.setFont(font)
        self.spinBoxSpeed_IN_10X.setMinimum(0)
        self.spinBoxSpeed_IN_10X.setMaximum(90)
        self.spinBoxSpeed_IN_10X.setSingleStep(10)
        self.spinBoxSpeed_IN_10X.setProperty("value", 90)
        self.spinBoxSpeed_IN_10X.setObjectName("spinBoxSpeed_IN_10X")
        self.spinBoxSpeed_IN_1X = QtWidgets.QSpinBox(self.groupBoxSet_Speed)
        self.spinBoxSpeed_IN_1X.setGeometry(QtCore.QRect(290, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxSpeed_IN_1X.setFont(font)
        self.spinBoxSpeed_IN_1X.setMinimum(0)
        self.spinBoxSpeed_IN_1X.setMaximum(10)
        self.spinBoxSpeed_IN_1X.setSingleStep(1)
        self.spinBoxSpeed_IN_1X.setProperty("value", 10)
        self.spinBoxSpeed_IN_1X.setObjectName("spinBoxSpeed_IN_1X")
        self.label_7 = QtWidgets.QLabel(self.groupBoxSet_Speed)
        self.label_7.setGeometry(QtCore.QRect(270, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBoxSet_Speed)
        self.label_8.setGeometry(QtCore.QRect(410, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBoxSet_Acceleration = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Acceleration.setGeometry(QtCore.QRect(0, 280, 671, 101))
        self.groupBoxSet_Acceleration.setObjectName("groupBoxSet_Acceleration")
        self.spinBoxAcceleration_IN_1000X = QtWidgets.QSpinBox(self.groupBoxSet_Acceleration)
        self.spinBoxAcceleration_IN_1000X.setGeometry(QtCore.QRect(10, 30, 150, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxAcceleration_IN_1000X.setFont(font)
        self.spinBoxAcceleration_IN_1000X.setMinimum(0)
        self.spinBoxAcceleration_IN_1000X.setMaximum(19000)
        self.spinBoxAcceleration_IN_1000X.setSingleStep(1000)
        self.spinBoxAcceleration_IN_1000X.setProperty("value", 19000)
        self.spinBoxAcceleration_IN_1000X.setObjectName("spinBoxAcceleration_IN_1000X")
        self.spinBoxAcceleration_IN_100X = QtWidgets.QSpinBox(self.groupBoxSet_Acceleration)
        self.spinBoxAcceleration_IN_100X.setGeometry(QtCore.QRect(180, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxAcceleration_IN_100X.setFont(font)
        self.spinBoxAcceleration_IN_100X.setMinimum(0)
        self.spinBoxAcceleration_IN_100X.setMaximum(900)
        self.spinBoxAcceleration_IN_100X.setSingleStep(100)
        self.spinBoxAcceleration_IN_100X.setProperty("value", 900)
        self.spinBoxAcceleration_IN_100X.setObjectName("spinBoxAcceleration_IN_100X")
        self.spinBoxAcceleration_IN_10X = QtWidgets.QSpinBox(self.groupBoxSet_Acceleration)
        self.spinBoxAcceleration_IN_10X.setGeometry(QtCore.QRect(320, 30, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxAcceleration_IN_10X.setFont(font)
        self.spinBoxAcceleration_IN_10X.setMinimum(0)
        self.spinBoxAcceleration_IN_10X.setMaximum(100)
        self.spinBoxAcceleration_IN_10X.setSingleStep(10)
        self.spinBoxAcceleration_IN_10X.setProperty("value", 100)
        self.spinBoxAcceleration_IN_10X.setObjectName("spinBoxAcceleration_IN_10X")
        self.label_10 = QtWidgets.QLabel(self.groupBoxSet_Acceleration)
        self.label_10.setGeometry(QtCore.QRect(300, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.groupBoxSet_Acceleration)
        self.label_9.setGeometry(QtCore.QRect(160, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_Acceleration_IN = QtWidgets.QLineEdit(self.groupBoxSet_Acceleration)
        self.lineEdit_Acceleration_IN.setGeometry(QtCore.QRect(460, 30, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lineEdit_Acceleration_IN.setFont(font)
        self.lineEdit_Acceleration_IN.setDragEnabled(False)
        self.lineEdit_Acceleration_IN.setReadOnly(True)
        self.lineEdit_Acceleration_IN.setObjectName("lineEdit_Acceleration_IN")
        self.label_11 = QtWidgets.QLabel(self.groupBoxSet_Acceleration)
        self.label_11.setGeometry(QtCore.QRect(440, 40, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.Tab_Manual, "")
        self.Tab_Settings = QtWidgets.QWidget()
        self.Tab_Settings.setObjectName("Tab_Settings")
        self.comboBoxSerialName = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialName.setGeometry(QtCore.QRect(170, 20, 331, 61))
        self.comboBoxSerialName.setObjectName("comboBoxSerialName")
        self.comboBoxSerialSpeed = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialSpeed.setGeometry(QtCore.QRect(170, 100, 151, 61))
        self.comboBoxSerialSpeed.setObjectName("comboBoxSerialSpeed")
        self.spinBoxPeriodDate = QtWidgets.QSpinBox(self.Tab_Settings)
        self.spinBoxPeriodDate.setGeometry(QtCore.QRect(170, 180, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.spinBoxPeriodDate.setFont(font)
        self.spinBoxPeriodDate.setMinimum(40)
        self.spinBoxPeriodDate.setMaximum(600)
        self.spinBoxPeriodDate.setSingleStep(20)
        self.spinBoxPeriodDate.setObjectName("spinBoxPeriodDate")
        self.label_3 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 131, 50))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 131, 50))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 131, 50))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.Tab_Settings, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(700, 20, 301, 481))
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setObjectName("groupBox")
        self.lcdPosition = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdPosition.setEnabled(True)
        self.lcdPosition.setGeometry(QtCore.QRect(130, 40, 151, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.lcdPosition.setPalette(palette)
        self.lcdPosition.setMouseTracking(False)
        self.lcdPosition.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdPosition.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdPosition.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdPosition.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdPosition.setLineWidth(2)
        self.lcdPosition.setMidLineWidth(10)
        self.lcdPosition.setSmallDecimalPoint(False)
        self.lcdPosition.setDigitCount(9)
        self.lcdPosition.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdPosition.setProperty("value", 0.0)
        self.lcdPosition.setProperty("intValue", 0)
        self.lcdPosition.setObjectName("lcdPosition")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 50))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 50))
        self.label_2.setObjectName("label_2")
        self.lcdSpeed = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdSpeed.setEnabled(True)
        self.lcdSpeed.setGeometry(QtCore.QRect(190, 100, 91, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.lcdSpeed.setPalette(palette)
        self.lcdSpeed.setMouseTracking(False)
        self.lcdSpeed.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdSpeed.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdSpeed.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdSpeed.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdSpeed.setLineWidth(2)
        self.lcdSpeed.setMidLineWidth(10)
        self.lcdSpeed.setSmallDecimalPoint(False)
        self.lcdSpeed.setDigitCount(5)
        self.lcdSpeed.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdSpeed.setProperty("value", 0.0)
        self.lcdSpeed.setProperty("intValue", 0)
        self.lcdSpeed.setObjectName("lcdSpeed")
        self.Acceleration_IN_Slider = QtWidgets.QSlider(self.centralwidget)
        self.Acceleration_IN_Slider.setGeometry(QtCore.QRect(100, 510, 651, 51))
        self.Acceleration_IN_Slider.setMaximum(20000)
        self.Acceleration_IN_Slider.setSingleStep(10)
        self.Acceleration_IN_Slider.setPageStep(100)
        self.Acceleration_IN_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Acceleration_IN_Slider.setObjectName("Acceleration_IN_Slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionasda = QtWidgets.QAction(MainWindow)
        self.actionasda.setObjectName("actionasda")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRJ Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Wheel), _translate("MainWindow", "Wheel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass), _translate("MainWindow", "Hourglass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass_Wheel), _translate("MainWindow", "Hourglass-Wheel"))
        self.ST1_ON_Button.setText(_translate("MainWindow", "Forward rotation start"))
        self.ST2_ON_Button.setText(_translate("MainWindow", "Reverse rotation start"))
        self.ST12_OFF_Button.setText(_translate("MainWindow", "Stop rotation"))
        self.groupBoxSet_Speed.setTitle(_translate("MainWindow", "Set speed (r/min)"))
        self.label_6.setText(_translate("MainWindow", "+"))
        self.label_7.setText(_translate("MainWindow", "+"))
        self.label_8.setText(_translate("MainWindow", "="))
        self.groupBoxSet_Acceleration.setTitle(_translate("MainWindow", "Set Acceleration (ms)"))
        self.label_10.setText(_translate("MainWindow", "+"))
        self.label_9.setText(_translate("MainWindow", "+"))
        self.label_11.setText(_translate("MainWindow", "="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Manual), _translate("MainWindow", "Manual"))
        self.label_3.setText(_translate("MainWindow", "Serial Name:"))
        self.label_4.setText(_translate("MainWindow", "Serial Speed:"))
        self.label_5.setText(_translate("MainWindow", "Period:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Settings), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Current parameter MRJ"))
        self.label.setText(_translate("MainWindow", "Position: "))
        self.label_2.setText(_translate("MainWindow", "Speed: "))
        self.actionasda.setText(_translate("MainWindow", "asda"))

