# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 566))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(205, 255, 217);")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("background-color: rgb(205, 255, 217);")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Wheel = QtWidgets.QWidget()
        self.Tab_Wheel.setObjectName("Tab_Wheel")
        self.groupBoxSet_Speed_Wheel = QtWidgets.QGroupBox(self.Tab_Wheel)
        self.groupBoxSet_Speed_Wheel.setGeometry(QtCore.QRect(5, 60, 671, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.groupBoxSet_Speed_Wheel.setFont(font)
        self.groupBoxSet_Speed_Wheel.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 173, 0);\n"
"    border-radius: 15px;\n"
"    margin-top: 0.85em;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBoxSet_Speed_Wheel.setObjectName("groupBoxSet_Speed_Wheel")
        self.lineEdit_Speed_Wheel_IN = QtWidgets.QLineEdit(self.groupBoxSet_Speed_Wheel)
        self.lineEdit_Speed_Wheel_IN.setGeometry(QtCore.QRect(260, 30, 121, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lineEdit_Speed_Wheel_IN.setFont(font)
        self.lineEdit_Speed_Wheel_IN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Speed_Wheel_IN.setDragEnabled(False)
        self.lineEdit_Speed_Wheel_IN.setReadOnly(True)
        self.lineEdit_Speed_Wheel_IN.setObjectName("lineEdit_Speed_Wheel_IN")
        self.button_Speed_Wheel_m1 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_m1.setGeometry(QtCore.QRect(160, 30, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_m1.setFont(font)
        self.button_Speed_Wheel_m1.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_m1.setObjectName("button_Speed_Wheel_m1")
        self.button_Speed_Wheel_m10 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_m10.setGeometry(QtCore.QRect(80, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_m10.setFont(font)
        self.button_Speed_Wheel_m10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_m10.setObjectName("button_Speed_Wheel_m10")
        self.button_Speed_Wheel_m100 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_m100.setGeometry(QtCore.QRect(10, 29, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_m100.setFont(font)
        self.button_Speed_Wheel_m100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_m100.setObjectName("button_Speed_Wheel_m100")
        self.button_Speed_Wheel_p1 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_p1.setGeometry(QtCore.QRect(390, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_p1.setFont(font)
        self.button_Speed_Wheel_p1.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_p1.setObjectName("button_Speed_Wheel_p1")
        self.button_Speed_Wheel_p10 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_p10.setGeometry(QtCore.QRect(500, 30, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_p10.setFont(font)
        self.button_Speed_Wheel_p10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_p10.setObjectName("button_Speed_Wheel_p10")
        self.button_Speed_Wheel_p100 = QtWidgets.QPushButton(self.groupBoxSet_Speed_Wheel)
        self.button_Speed_Wheel_p100.setGeometry(QtCore.QRect(590, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.button_Speed_Wheel_p100.setFont(font)
        self.button_Speed_Wheel_p100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_Wheel_p100.setObjectName("button_Speed_Wheel_p100")
        self.ST2_ON_Button_Wheel = QtWidgets.QPushButton(self.Tab_Wheel)
        self.ST2_ON_Button_Wheel.setGeometry(QtCore.QRect(10, 10, 241, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST2_ON_Button_Wheel.setFont(font)
        self.ST2_ON_Button_Wheel.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST2_ON_Button_Wheel.setObjectName("ST2_ON_Button_Wheel")
        self.ST12_OFF_Button_Wheel = QtWidgets.QPushButton(self.Tab_Wheel)
        self.ST12_OFF_Button_Wheel.setGeometry(QtCore.QRect(260, 10, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST12_OFF_Button_Wheel.setFont(font)
        self.ST12_OFF_Button_Wheel.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST12_OFF_Button_Wheel.setObjectName("ST12_OFF_Button_Wheel")
        self.ST1_ON_Button_Wheel = QtWidgets.QPushButton(self.Tab_Wheel)
        self.ST1_ON_Button_Wheel.setGeometry(QtCore.QRect(430, 10, 251, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST1_ON_Button_Wheel.setFont(font)
        self.ST1_ON_Button_Wheel.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST1_ON_Button_Wheel.setObjectName("ST1_ON_Button_Wheel")
        self.tabWidget.addTab(self.Tab_Wheel, "")
        self.Tab_Hourglass = QtWidgets.QWidget()
        self.Tab_Hourglass.setObjectName("Tab_Hourglass")
        self.tabWidget.addTab(self.Tab_Hourglass, "")
        self.Tab_Hourglass_Wheel = QtWidgets.QWidget()
        self.Tab_Hourglass_Wheel.setObjectName("Tab_Hourglass_Wheel")
        self.tabWidget.addTab(self.Tab_Hourglass_Wheel, "")
        self.Tab_Manual = QtWidgets.QWidget()
        self.Tab_Manual.setObjectName("Tab_Manual")
        self.ST1_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST1_ON_Button.setGeometry(QtCore.QRect(430, 10, 251, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST1_ON_Button.setFont(font)
        self.ST1_ON_Button.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST1_ON_Button.setObjectName("ST1_ON_Button")
        self.ST2_ON_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST2_ON_Button.setGeometry(QtCore.QRect(10, 10, 241, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST2_ON_Button.setFont(font)
        self.ST2_ON_Button.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST2_ON_Button.setObjectName("ST2_ON_Button")
        self.ST12_OFF_Button = QtWidgets.QPushButton(self.Tab_Manual)
        self.ST12_OFF_Button.setGeometry(QtCore.QRect(260, 10, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.ST12_OFF_Button.setFont(font)
        self.ST12_OFF_Button.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.ST12_OFF_Button.setObjectName("ST12_OFF_Button")
        self.groupBoxSet_Speed = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Speed.setGeometry(QtCore.QRect(5, 60, 671, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.groupBoxSet_Speed.setFont(font)
        self.groupBoxSet_Speed.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 173, 0);\n"
"    border-radius: 15px;\n"
"    margin-top: 0.85em;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBoxSet_Speed.setObjectName("groupBoxSet_Speed")
        self.lineEdit_Speed_IN = QtWidgets.QLineEdit(self.groupBoxSet_Speed)
        self.lineEdit_Speed_IN.setGeometry(QtCore.QRect(270, 31, 101, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lineEdit_Speed_IN.setFont(font)
        self.lineEdit_Speed_IN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Speed_IN.setDragEnabled(False)
        self.lineEdit_Speed_IN.setReadOnly(True)
        self.lineEdit_Speed_IN.setObjectName("lineEdit_Speed_IN")
        self.button_Speed_m1 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m1.setGeometry(QtCore.QRect(190, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_m1.setFont(font)
        self.button_Speed_m1.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_m1.setObjectName("button_Speed_m1")
        self.button_Speed_m10 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m10.setGeometry(QtCore.QRect(110, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_m10.setFont(font)
        self.button_Speed_m10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_m10.setObjectName("button_Speed_m10")
        self.button_Speed_m100 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_m100.setGeometry(QtCore.QRect(10, 29, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_m100.setFont(font)
        self.button_Speed_m100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_m100.setObjectName("button_Speed_m100")
        self.button_Speed_p1 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p1.setGeometry(QtCore.QRect(380, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_p1.setFont(font)
        self.button_Speed_p1.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_p1.setObjectName("button_Speed_p1")
        self.button_Speed_p10 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p10.setGeometry(QtCore.QRect(460, 30, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_p10.setFont(font)
        self.button_Speed_p10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_p10.setObjectName("button_Speed_p10")
        self.button_Speed_p100 = QtWidgets.QPushButton(self.groupBoxSet_Speed)
        self.button_Speed_p100.setGeometry(QtCore.QRect(550, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.button_Speed_p100.setFont(font)
        self.button_Speed_p100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Speed_p100.setObjectName("button_Speed_p100")
        self.groupBoxSet_Acceleration = QtWidgets.QGroupBox(self.Tab_Manual)
        self.groupBoxSet_Acceleration.setGeometry(QtCore.QRect(5, 160, 671, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.groupBoxSet_Acceleration.setFont(font)
        self.groupBoxSet_Acceleration.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 173, 0);\n"
"    border-radius: 15px;\n"
"    margin-top: 0.85em;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBoxSet_Acceleration.setObjectName("groupBoxSet_Acceleration")
        self.lineEdit_Acceleration_IN = QtWidgets.QLineEdit(self.groupBoxSet_Acceleration)
        self.lineEdit_Acceleration_IN.setGeometry(QtCore.QRect(270, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.lineEdit_Acceleration_IN.setFont(font)
        self.lineEdit_Acceleration_IN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Acceleration_IN.setDragEnabled(False)
        self.lineEdit_Acceleration_IN.setReadOnly(True)
        self.lineEdit_Acceleration_IN.setObjectName("lineEdit_Acceleration_IN")
        self.button_Acceleration_m1000 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m1000.setGeometry(QtCore.QRect(10, 30, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_m1000.setFont(font)
        self.button_Acceleration_m1000.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_m1000.setObjectName("button_Acceleration_m1000")
        self.button_Acceleration_m100 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m100.setGeometry(QtCore.QRect(110, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_m100.setFont(font)
        self.button_Acceleration_m100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_m100.setObjectName("button_Acceleration_m100")
        self.button_Acceleration_m10 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_m10.setGeometry(QtCore.QRect(190, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_m10.setFont(font)
        self.button_Acceleration_m10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_m10.setObjectName("button_Acceleration_m10")
        self.button_Acceleration_p10 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p10.setGeometry(QtCore.QRect(380, 30, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_p10.setFont(font)
        self.button_Acceleration_p10.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_p10.setObjectName("button_Acceleration_p10")
        self.button_Acceleration_p100 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p100.setGeometry(QtCore.QRect(460, 30, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_p100.setFont(font)
        self.button_Acceleration_p100.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_p100.setObjectName("button_Acceleration_p100")
        self.button_Acceleration_p1000 = QtWidgets.QPushButton(self.groupBoxSet_Acceleration)
        self.button_Acceleration_p1000.setGeometry(QtCore.QRect(550, 30, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.button_Acceleration_p1000.setFont(font)
        self.button_Acceleration_p1000.setStyleSheet("background-color: rgb(146, 255, 210);")
        self.button_Acceleration_p1000.setObjectName("button_Acceleration_p1000")
        self.tabWidget.addTab(self.Tab_Manual, "")
        self.Tab_Settings = QtWidgets.QWidget()
        self.Tab_Settings.setObjectName("Tab_Settings")
        self.comboBoxSerialName = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialName.setGeometry(QtCore.QRect(180, 10, 261, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBoxSerialName.setFont(font)
        self.comboBoxSerialName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxSerialName.setObjectName("comboBoxSerialName")
        self.comboBoxSerialSpeed = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxSerialSpeed.setGeometry(QtCore.QRect(180, 60, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBoxSerialSpeed.setFont(font)
        self.comboBoxSerialSpeed.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxSerialSpeed.setObjectName("comboBoxSerialSpeed")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.comboBoxSerialSpeed.addItem("")
        self.label_3 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_3.setGeometry(QtCore.QRect(5, 10, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_4.setGeometry(QtCore.QRect(5, 60, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_5.setGeometry(QtCore.QRect(5, 110, 151, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_Save_Settings = QtWidgets.QPushButton(self.Tab_Settings)
        self.pushButton_Save_Settings.setGeometry(QtCore.QRect(460, 100, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.pushButton_Save_Settings.setFont(font)
        self.pushButton_Save_Settings.setStyleSheet("background-color: rgb(67, 255, 98);")
        self.pushButton_Save_Settings.setObjectName("pushButton_Save_Settings")
        self.label_6 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_6.setGeometry(QtCore.QRect(5, 160, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBoxMRJ_type = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxMRJ_type.setGeometry(QtCore.QRect(180, 160, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBoxMRJ_type.setFont(font)
        self.comboBoxMRJ_type.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxMRJ_type.setObjectName("comboBoxMRJ_type")
        self.comboBoxMRJ_type.addItem("")
        self.comboBoxMRJ_type.addItem("")
        self.label_7 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_7.setGeometry(QtCore.QRect(5, 210, 261, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBoxStation_number = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxStation_number.setGeometry(QtCore.QRect(270, 210, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBoxStation_number.setFont(font)
        self.comboBoxStation_number.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxStation_number.setObjectName("comboBoxStation_number")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxStation_number.addItem("")
        self.comboBoxPeriodDate = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBoxPeriodDate.setGeometry(QtCore.QRect(180, 110, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBoxPeriodDate.setFont(font)
        self.comboBoxPeriodDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxPeriodDate.setObjectName("comboBoxPeriodDate")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.comboBoxPeriodDate.addItem("")
        self.label_8 = QtWidgets.QLabel(self.Tab_Settings)
        self.label_8.setGeometry(QtCore.QRect(5, 260, 541, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_NL = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBox_NL.setGeometry(QtCore.QRect(350, 260, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBox_NL.setFont(font)
        self.comboBox_NL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_NL.setObjectName("comboBox_NL")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NL.addItem("")
        self.comboBox_NM = QtWidgets.QComboBox(self.Tab_Settings)
        self.comboBox_NM.setGeometry(QtCore.QRect(520, 260, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.comboBox_NM.setFont(font)
        self.comboBox_NM.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_NM.setObjectName("comboBox_NM")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.comboBox_NM.addItem("")
        self.tabWidget.addTab(self.Tab_Settings, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(700, 20, 301, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(0, 173, 0);\n"
"    border-radius: 15px;\n"
"    margin-top: 0.85em;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setObjectName("groupBox")
        self.lcdPosition = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdPosition.setEnabled(True)
        self.lcdPosition.setGeometry(QtCore.QRect(130, 40, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lcdPosition.setFont(font)
        self.lcdPosition.setMouseTracking(False)
        self.lcdPosition.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdPosition.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdPosition.setLineWidth(0)
        self.lcdPosition.setMidLineWidth(2)
        self.lcdPosition.setSmallDecimalPoint(False)
        self.lcdPosition.setDigitCount(9)
        self.lcdPosition.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdPosition.setProperty("value", 0.0)
        self.lcdPosition.setProperty("intValue", 0)
        self.lcdPosition.setObjectName("lcdPosition")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lcdSpeed = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdSpeed.setEnabled(True)
        self.lcdSpeed.setGeometry(QtCore.QRect(190, 100, 91, 50))
        self.lcdSpeed.setMouseTracking(False)
        self.lcdSpeed.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lcdSpeed.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdSpeed.setLineWidth(0)
        self.lcdSpeed.setMidLineWidth(2)
        self.lcdSpeed.setSmallDecimalPoint(False)
        self.lcdSpeed.setDigitCount(5)
        self.lcdSpeed.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdSpeed.setProperty("value", 0.0)
        self.lcdSpeed.setProperty("intValue", 0)
        self.lcdSpeed.setObjectName("lcdSpeed")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(739, 230, 231, 221))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"border: 1px solid gray;\n"
"border-color: #FF17365D;\n"
"margin-top: 27px;\n"
"font-size: 14px;\n"
"border-radius: 15px;\n"
"}\n"
"QGroupBox::title {\n"
"border-top-left-radius: 9px;\n"
"border-top-right-radius: 9px;\n"
"padding: 2px 82px;\n"
"background-color: #FF17365D;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionasda = QtWidgets.QAction(MainWindow)
        self.actionasda.setObjectName("actionasda")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_NM.setCurrentIndex(49)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRJ Control"))
        self.groupBoxSet_Speed_Wheel.setTitle(_translate("MainWindow", "Set speed, r/min"))
        self.lineEdit_Speed_Wheel_IN.setText(_translate("MainWindow", "150.00"))
        self.button_Speed_Wheel_m1.setText(_translate("MainWindow", "-0.025"))
        self.button_Speed_Wheel_m10.setText(_translate("MainWindow", "-0.25"))
        self.button_Speed_Wheel_m100.setText(_translate("MainWindow", "-9.5"))
        self.button_Speed_Wheel_p1.setText(_translate("MainWindow", "+0.025"))
        self.button_Speed_Wheel_p10.setText(_translate("MainWindow", "+0.25"))
        self.button_Speed_Wheel_p100.setText(_translate("MainWindow", "+9.5"))
        self.ST2_ON_Button_Wheel.setText(_translate("MainWindow", "Start reverse rotation"))
        self.ST12_OFF_Button_Wheel.setText(_translate("MainWindow", "Stop rotation"))
        self.ST1_ON_Button_Wheel.setText(_translate("MainWindow", "Start forward rotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Wheel), _translate("MainWindow", "Wheel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass), _translate("MainWindow", "Hourglass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Hourglass_Wheel), _translate("MainWindow", "Hourglass-Wheel"))
        self.ST1_ON_Button.setText(_translate("MainWindow", "Start forward rotation"))
        self.ST2_ON_Button.setText(_translate("MainWindow", "Start reverse rotation"))
        self.ST12_OFF_Button.setText(_translate("MainWindow", "Stop rotation"))
        self.groupBoxSet_Speed.setTitle(_translate("MainWindow", "Set speed, r/min(0...3000)"))
        self.lineEdit_Speed_IN.setText(_translate("MainWindow", "3000"))
        self.button_Speed_m1.setText(_translate("MainWindow", "-1"))
        self.button_Speed_m10.setText(_translate("MainWindow", "-10"))
        self.button_Speed_m100.setText(_translate("MainWindow", "-100"))
        self.button_Speed_p1.setText(_translate("MainWindow", "+1"))
        self.button_Speed_p10.setText(_translate("MainWindow", "+10"))
        self.button_Speed_p100.setText(_translate("MainWindow", "+100"))
        self.groupBoxSet_Acceleration.setTitle(_translate("MainWindow", "Set Acceleration, ms(500...20000)"))
        self.lineEdit_Acceleration_IN.setText(_translate("MainWindow", "20000"))
        self.button_Acceleration_m1000.setText(_translate("MainWindow", "-1000"))
        self.button_Acceleration_m100.setText(_translate("MainWindow", "-100"))
        self.button_Acceleration_m10.setText(_translate("MainWindow", "-10"))
        self.button_Acceleration_p10.setText(_translate("MainWindow", "+10"))
        self.button_Acceleration_p100.setText(_translate("MainWindow", "+100"))
        self.button_Acceleration_p1000.setText(_translate("MainWindow", "+1000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Manual), _translate("MainWindow", "Manual"))
        self.comboBoxSerialSpeed.setItemText(0, _translate("MainWindow", "57600"))
        self.comboBoxSerialSpeed.setItemText(1, _translate("MainWindow", "38400"))
        self.comboBoxSerialSpeed.setItemText(2, _translate("MainWindow", "19200"))
        self.comboBoxSerialSpeed.setItemText(3, _translate("MainWindow", "9600"))
        self.label_3.setText(_translate("MainWindow", "Serial Name:"))
        self.label_4.setText(_translate("MainWindow", "Serial Speed:"))
        self.label_5.setText(_translate("MainWindow", "Period, ms:"))
        self.pushButton_Save_Settings.setText(_translate("MainWindow", "Save Settings"))
        self.label_6.setText(_translate("MainWindow", "MRJ type:"))
        self.comboBoxMRJ_type.setItemText(0, _translate("MainWindow", "J2S-xCL"))
        self.comboBoxMRJ_type.setItemText(1, _translate("MainWindow", "J2S-xA"))
        self.label_7.setText(_translate("MainWindow", "MRJ Station number:"))
        self.comboBoxStation_number.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxStation_number.setItemText(1, _translate("MainWindow", "1"))
        self.comboBoxStation_number.setItemText(2, _translate("MainWindow", "2"))
        self.comboBoxStation_number.setItemText(3, _translate("MainWindow", "3"))
        self.comboBoxStation_number.setItemText(4, _translate("MainWindow", "4"))
        self.comboBoxStation_number.setItemText(5, _translate("MainWindow", "5"))
        self.comboBoxStation_number.setItemText(6, _translate("MainWindow", "6"))
        self.comboBoxStation_number.setItemText(7, _translate("MainWindow", "7"))
        self.comboBoxStation_number.setItemText(8, _translate("MainWindow", "8"))
        self.comboBoxStation_number.setItemText(9, _translate("MainWindow", "9"))
        self.comboBoxStation_number.setItemText(10, _translate("MainWindow", "A"))
        self.comboBoxStation_number.setItemText(11, _translate("MainWindow", "B"))
        self.comboBoxStation_number.setItemText(12, _translate("MainWindow", "C"))
        self.comboBoxStation_number.setItemText(13, _translate("MainWindow", "D"))
        self.comboBoxStation_number.setItemText(14, _translate("MainWindow", "E"))
        self.comboBoxPeriodDate.setItemText(0, _translate("MainWindow", "50"))
        self.comboBoxPeriodDate.setItemText(1, _translate("MainWindow", "100"))
        self.comboBoxPeriodDate.setItemText(2, _translate("MainWindow", "150"))
        self.comboBoxPeriodDate.setItemText(3, _translate("MainWindow", "200"))
        self.comboBoxPeriodDate.setItemText(4, _translate("MainWindow", "250"))
        self.comboBoxPeriodDate.setItemText(5, _translate("MainWindow", "300"))
        self.comboBoxPeriodDate.setItemText(6, _translate("MainWindow", "350"))
        self.comboBoxPeriodDate.setItemText(7, _translate("MainWindow", "400"))
        self.comboBoxPeriodDate.setItemText(8, _translate("MainWindow", "450"))
        self.comboBoxPeriodDate.setItemText(9, _translate("MainWindow", "500"))
        self.comboBoxPeriodDate.setItemText(10, _translate("MainWindow", "550"))
        self.comboBoxPeriodDate.setItemText(11, _translate("MainWindow", "600"))
        self.label_8.setText(_translate("MainWindow", "Reduction ratio NL/NM: NL=            , NM="))
        self.comboBox_NL.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_NL.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_NL.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_NL.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_NL.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_NL.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_NL.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_NL.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_NL.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_NL.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_NL.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_NL.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_NL.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_NL.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_NL.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_NL.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_NL.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_NL.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_NL.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_NL.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_NL.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_NL.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_NL.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_NL.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_NL.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_NL.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_NL.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_NL.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_NL.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_NL.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_NL.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_NL.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_NL.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_NL.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_NL.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_NL.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_NL.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_NL.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_NL.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_NL.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_NL.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_NL.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_NL.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_NL.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_NL.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_NL.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_NL.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_NL.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_NL.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_NL.setItemText(49, _translate("MainWindow", "50"))
        self.comboBox_NL.setItemText(50, _translate("MainWindow", "51"))
        self.comboBox_NL.setItemText(51, _translate("MainWindow", "52"))
        self.comboBox_NL.setItemText(52, _translate("MainWindow", "53"))
        self.comboBox_NL.setItemText(53, _translate("MainWindow", "54"))
        self.comboBox_NL.setItemText(54, _translate("MainWindow", "55"))
        self.comboBox_NL.setItemText(55, _translate("MainWindow", "56"))
        self.comboBox_NL.setItemText(56, _translate("MainWindow", "57"))
        self.comboBox_NL.setItemText(57, _translate("MainWindow", "58"))
        self.comboBox_NL.setItemText(58, _translate("MainWindow", "59"))
        self.comboBox_NL.setItemText(59, _translate("MainWindow", "60"))
        self.comboBox_NL.setItemText(60, _translate("MainWindow", "61"))
        self.comboBox_NL.setItemText(61, _translate("MainWindow", "62"))
        self.comboBox_NL.setItemText(62, _translate("MainWindow", "63"))
        self.comboBox_NL.setItemText(63, _translate("MainWindow", "64"))
        self.comboBox_NL.setItemText(64, _translate("MainWindow", "65"))
        self.comboBox_NL.setItemText(65, _translate("MainWindow", "66"))
        self.comboBox_NL.setItemText(66, _translate("MainWindow", "67"))
        self.comboBox_NL.setItemText(67, _translate("MainWindow", "68"))
        self.comboBox_NL.setItemText(68, _translate("MainWindow", "69"))
        self.comboBox_NL.setItemText(69, _translate("MainWindow", "70"))
        self.comboBox_NL.setItemText(70, _translate("MainWindow", "71"))
        self.comboBox_NL.setItemText(71, _translate("MainWindow", "72"))
        self.comboBox_NL.setItemText(72, _translate("MainWindow", "73"))
        self.comboBox_NL.setItemText(73, _translate("MainWindow", "74"))
        self.comboBox_NL.setItemText(74, _translate("MainWindow", "75"))
        self.comboBox_NL.setItemText(75, _translate("MainWindow", "76"))
        self.comboBox_NL.setItemText(76, _translate("MainWindow", "77"))
        self.comboBox_NL.setItemText(77, _translate("MainWindow", "78"))
        self.comboBox_NL.setItemText(78, _translate("MainWindow", "79"))
        self.comboBox_NL.setItemText(79, _translate("MainWindow", "80"))
        self.comboBox_NM.setCurrentText(_translate("MainWindow", "50"))
        self.comboBox_NM.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_NM.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_NM.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_NM.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_NM.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_NM.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_NM.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_NM.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_NM.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_NM.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_NM.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_NM.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_NM.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_NM.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_NM.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_NM.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_NM.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_NM.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_NM.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_NM.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_NM.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_NM.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_NM.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_NM.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_NM.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_NM.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_NM.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_NM.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_NM.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_NM.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_NM.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_NM.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_NM.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_NM.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_NM.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_NM.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_NM.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_NM.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_NM.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_NM.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_NM.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_NM.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_NM.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_NM.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_NM.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_NM.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_NM.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_NM.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_NM.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_NM.setItemText(49, _translate("MainWindow", "50"))
        self.comboBox_NM.setItemText(50, _translate("MainWindow", "51"))
        self.comboBox_NM.setItemText(51, _translate("MainWindow", "52"))
        self.comboBox_NM.setItemText(52, _translate("MainWindow", "53"))
        self.comboBox_NM.setItemText(53, _translate("MainWindow", "54"))
        self.comboBox_NM.setItemText(54, _translate("MainWindow", "55"))
        self.comboBox_NM.setItemText(55, _translate("MainWindow", "56"))
        self.comboBox_NM.setItemText(56, _translate("MainWindow", "57"))
        self.comboBox_NM.setItemText(57, _translate("MainWindow", "58"))
        self.comboBox_NM.setItemText(58, _translate("MainWindow", "59"))
        self.comboBox_NM.setItemText(59, _translate("MainWindow", "60"))
        self.comboBox_NM.setItemText(60, _translate("MainWindow", "61"))
        self.comboBox_NM.setItemText(61, _translate("MainWindow", "62"))
        self.comboBox_NM.setItemText(62, _translate("MainWindow", "63"))
        self.comboBox_NM.setItemText(63, _translate("MainWindow", "64"))
        self.comboBox_NM.setItemText(64, _translate("MainWindow", "65"))
        self.comboBox_NM.setItemText(65, _translate("MainWindow", "66"))
        self.comboBox_NM.setItemText(66, _translate("MainWindow", "67"))
        self.comboBox_NM.setItemText(67, _translate("MainWindow", "68"))
        self.comboBox_NM.setItemText(68, _translate("MainWindow", "69"))
        self.comboBox_NM.setItemText(69, _translate("MainWindow", "70"))
        self.comboBox_NM.setItemText(70, _translate("MainWindow", "71"))
        self.comboBox_NM.setItemText(71, _translate("MainWindow", "72"))
        self.comboBox_NM.setItemText(72, _translate("MainWindow", "73"))
        self.comboBox_NM.setItemText(73, _translate("MainWindow", "74"))
        self.comboBox_NM.setItemText(74, _translate("MainWindow", "75"))
        self.comboBox_NM.setItemText(75, _translate("MainWindow", "76"))
        self.comboBox_NM.setItemText(76, _translate("MainWindow", "77"))
        self.comboBox_NM.setItemText(77, _translate("MainWindow", "78"))
        self.comboBox_NM.setItemText(78, _translate("MainWindow", "79"))
        self.comboBox_NM.setItemText(79, _translate("MainWindow", "80"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Settings), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Current parameter MRJ"))
        self.label.setText(_translate("MainWindow", "Position: "))
        self.label_2.setText(_translate("MainWindow", "Speed: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.actionasda.setText(_translate("MainWindow", "asda"))

